# Configuration file for BMD GWAS analysis workflow

# Input files
input_gwas: "/mnt/10T-backup-mingju/ifar/gwas/eBMD/EPFinder_preprocessing/eBMD_OpenChromatin_OB_EPFinder_input.tsv"

# bedtools
bedtools_path: "/usr/bin/bedtools"


# Hi-C data
hic_folder: "/mnt/10T-backup-mingju/ifar/Hi-C/OB/3k"
hic_prefix: "OB13.bam.pre.filter.q30.3k.hic.KR."

# Genome annotations
tss_file: "/mnt/10T-backup-mingju/ifar/databases/hg38/GeneBased/ensGene/gencode29/gencode.v29.annotation.gtf.pcg.tss_sorted_lexicographical"

# Expression data
tx_expression: "/mnt/10T-backup-mingju/ifar/ENCODE/osteoblast/RNAseq/osteoblast_RNAseq_tx_ENCFF220VSM.tsv.simple"
gene_list: "/mnt/10T-backup-mingju/ifar/databases/hg38/GeneBased/ensGene/gencode29/gencode.v29.annotation.gtf_gene.txt"
gene_expression: "/mnt/10T-backup-mingju/ifar/ENCODE/osteoblast/RNAseq/osteoblast_RNAseq_gene_ENCFF220VSM.tsv.simple"

# Feature files
feature_list: "/home/mingju/EPFinder/preprocessing/feature_list"

# Parameters
enhancer_window: 250  # bp around SNP for enhancer
promoter_window: 250  # bp around TSS for promoter
hic_bin_size: 3000    # Hi-C bin size

# Output directory
output_dir: "/mnt/10T-backup-mingju/ifar/gwas/eBMD/EPFinder_preprocessing" 
# Final output file name
output_file: "eBMD_OpenChromatin_SNPs_29features_ML.tsv"

# number of threads in step1
step1_nproc: 24
